---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
    name: csi.huawei.com
    labels:
        provisioner: csi.huawei.com
  {{- include "helm_lib_module_labels" (list . (dict "app" "csi-driver")) | nindent 2 }}
spec:
    attachRequired: false
    fsGroupPolicy: File
