{{- include "helm_lib_csi_controller_rbac" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node
  namespace: d8-{{ .Chart.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: d8:{{ .Chart.Name }}:csi:node
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets","configmaps" ]
    verbs: [ "get","update","create" ]
  - apiGroups: [ "xuanwu.huawei.io" ]
    resources: [ "storagebackendclaims","storagebackendcontents" ]
    verbs: [ "get" ]
  - apiGroups: [ "xuanwu.huawei.io" ]
    resources: [ "resourcetopologies" ]
    verbs: [ "create", "get", "update", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list","get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: d8:{{ .Chart.Name }}:csi:node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: d8:{{ .Chart.Name }}:csi:node
subjects:
  - kind: ServiceAccount
    name: csi-node
    namespace: d8-{{ .Chart.Name }}